# This is a basic workflow to help you get started with Actions

name: Docker Build (default)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, docker-swarm ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker-default:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clear old build
      run: rm -rf ./.build/

    - name: Generate Dockerfile
      run: ./generate-Dockerfile.sh -c latest --pw ${{ secrets.JUPYTER_PASSWORD }}
    
    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: ./.build
        file: ./.build/Dockerfile
        push: true
        tags: gpu-playground:latest
  
  docker-slim:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clear old build
      run: rm -rf ./.build/

    - name: Generate Dockerfile
      run: ./generate-Dockerfile.sh --slim -c latest --pw ${{ secrets.JUPYTER_PASSWORD }}
    
    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: ./.build
        file: ./.build/Dockerfile
        push: true
        tags: gpu-playground:slim